#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# why would you type 'cd dir' if you could just type 'dir'?
setopt AUTO_CD

# If we have a glob this will expand it
setopt GLOB_COMPLETE

# Case insensitive globbing
setopt NO_CASE_GLOB

# history
setopt SHARE_HISTORY
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt INC_APPEND_HISTORY
setopt HIST_SAVE_NO_DUPS

# Who doesn't want home and end to work?
bindkey '\e[1~' beginning-of-line
bindkey '\e[4~' end-of-line

# Incremental search is elite!
bindkey -M vicmd "/" history-incremental-search-backward
bindkey -M vicmd "?" history-incremental-search-forward

# Search based on what you typed in already
bindkey -M vicmd "//" history-beginning-search-backward
bindkey -M vicmd "??" history-beginning-search-forward

bindkey "\eOP" run-help

# oh wow!  This is killer...  try it!
bindkey -M vicmd "q" push-line

# it's like, space AND completion.  Gnarlbot.
bindkey -M viins ' ' magic-space


# aliases
alias du="du -h -s"
alias df="df -h"
unalias py
alias py="ipython"


if [ "$(uname)" = "Darwin" ]; then
    # Do something under Mac OS X platform
    alias ls='ls -hlaG'

    # Homebrew support
    export HOMEBREW_GITHUB_API_TOKEN=4b3976b1c6d01d180716cd78c5c730d30be89365
else
    # Do something under Linux platform
    alias ls='ls -hla --color=auto'
fi

